config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :reviews do
      member do
        get :profile
      end
      
    end
  end
  resources :authors do 
    member do
      get :personal_details 
    end
  end
  resources :users 
  root 'welcome#home'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?

    else
      can :update, book do |book|
        book.user ==

    end
  
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_one_attached :pic
    belongs_to :user
    
end

app/models/book.rb
class Book < ApplicationRecord

    has_one_attached :image
    has_many :reviews, dependent: :delete_all
    belongs_to :user
    
    

end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :book

    STAR=%w{1_star 2_star 3_star 4_star 5_star}

    validates :r_name, :r_desc, presence:true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
  has_one :authors

  enum :role, { writer: 0, reviewer: 1, admin: 2 }

  before_save {self.email=email.downcase}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  
    validates :email, presence: true, length: { maximum: 105 },            
                     uniqueness: { case_sensitive: false },            
                     format: { with: VALID_EMAIL_REGEX }

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_back(fallback_location: root_path)
  end
  helper_method :admin?
  helper_method :writer?
  helper_method :reviewer?
  def admin?
    current_user && current_user.role == "admin"
  end
  def writer?
    current_user && current_user.role == "writer"
  end
  def reviewer?
    current_user && current_user.role == "reviewer"
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_user!, except: [:index,:show]
    
    def index
        @authors = Author.all
    end
    
    def new
      @author = Author.new
    # @user = current_user
    end
    
    def create
      @user = current_user.id
      @author = Author.new(params.require(:author).permit(:name,:about,:experience,:written_books,:dob,:address,:email,:pic))
      @author.user_id = @user
      if @author.save 
        flash[:success] = "You have successfully entered your details"
        redirect_to root_path
      else
        render 'new'
      end
    end
    
    def show
      @author = Author.find(params[:id])
      
      if is_available
        @author = find_author
      else
        redirect_to new_author_path
      end
    end
    
    def edit
      @author = Author.find(params[:id])
    end

    def personal_details
      @author = Author.find(params[:id])
    end

    def update
      @author = Author.find(params[:id])
      if @author.update(params.require(:author).permit(:name,:about,:experience,:written_books,:dob,:address,:email,:pic))
        flash[:success] = "You have successfully updated your information"
        redirect_to root_path(@author)
      else
        render 'new'
      end
    end
    
    def destroy
      @author = Author.find(params[:id])
      @author.destroy
      redirect_to root_path
    end
    
    def is_available
      return Author.find_by(:user_id => current_user)
    end
    
    def find_author
      return Author.find_by(:user_id => current_user)
    end
    
    end
    

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    before_action :authenticate_user!, except: [:index,:show]
   
    

    def index
       @book = Book.all
    end

    def new
       @book = Book.new
    end

    def create
    @user = current_user.id
    @book = Book.new(params.require(:book).permit(:book_name,:description,:published_date,:image))
    @book.user_id = @user
       if @book.save 
            WelcomeNotificationMailer.create_notification(@book).deliver_now
           flash[:success] = "You have successfully entered your details"
           redirect_to root_path
       else
           render 'new'
       end
   end

   def show
       @book = Book.find(params[:id])
       @authors=Author.find(params[:id])
       
   end

   def edit
        @book = Book.find(params[:id])
   end
    
   def update
        @book = Book.find(params[:id])
       if @book.update(params.require(:book).permit(:book_name,:description,:published_date,:image))
        
           flash[:success] = "You have successfully updated your information"
           redirect_to books_path(@book)
       else
           render 'new'
       end
   end

   def destroy
        @book = Book.find(params[:id])
       @book.destroy
       redirect_to books_path
   end

   

end

app/controllers/registrations_controller.rb
# class RegistrationsController < Devise::RegistrationsController

#     private
    
#     def sign_up_params
    
#         params.require(:user).permit(:email,:password,:password_confirmation)
    
#     end
    
#     def account_update_params
    
#         params.require(:user).permit(:email,:password,:password_confirmation,:current_password)
    
#     end
    
#  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  
   
        def create
          @book = Book.find(params[:book_id])
          @review = @book.reviews.create(review_params)
          redirect_to book_path(@book)
        end

        def index
          @review=Review.all
        end

        def profile
          @book = Book.find(params[:book_id])
          @reviews=@book.reviews
        end

      
        private
          def review_params
            params.require(:review).permit(:r_name, :r_desc, :star, :birth,:locality,:interested)
          end
      

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
    def index 
        @users =User.all
        
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(params.require(:user).permit(:role))
          flash[:success]="Profile is updated successfully" 
          redirect_to users_path(@user)
        else
          render 'edit'
        end
    end

    def show
      @user = User.find(params[:id])
      @k=@user.books    
    end    

   

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/edit.html.erb
<h1 style="text-align:center;color:white;background-color:red">Edit Author Detail</h1>

<%= form_with model: @author do |f| %>
  <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
      <strong><%= f.label :enter_author_name %></strong>
      <%= f.text_field :name, placeholder: "Enter Author Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :about %></strong>
      <%= f.text_field :about, placeholder: "Enter about Author", autofocus: true %>
    
    </div>

    <div class="column mb-3">
      <strong><%= f.label :enter_experience %></strong>
      <%= f.number_field :experience, placeholder: "Enter Experience Year", autofocus: true %>
    
    </div>
  
    <div class="row mb-3">
      <strong><%= f.label :total_written_books %></strong>
      <%= f.number_field :written_books, placeholder: "Image of book", autofocus: true %>
    
    </div>

    <div class="column mb-3">
      <strong><%= f.label :date_of_birth %></strong>
      <%= f.text_field :dob, placeholder: "", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :author_email %></strong>
      <%= f.email_field :email, placeholder: "Write author's email", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :authors_address %></strong>
      <%= f.text_field :address, placeholder: "Enter Authors Address", autofocus: true %>
    
    </div>    
 
    <div class="row mb-3">
      <Strong><%= f.label :Chhose_Your_Profile_Pic %></strong>
      <%= f.file_field :pic %>
    
    </div>

    

    
  
  <%= f.submit "submit", class:"btn btn-success " %>
  </div>

  
  
<%end%>

app/views/authors/index.html.erb
<h1 style="text-align:center;color:white;background-color:red">All Registered Author Detail</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Serial Number</th>
      <th scope="col">Name</th>
      <th scope="col">About</th>
      <th scope="col">Experience</th>
      <th scope="col">Date Of Birth</th>
      <th scope="col">Address</th>
      <th scope="col">Email</th>
      <th scope="col">Created Date/Time</th>
      <th scope="col">Updated Date/Time</th>
      <th scope="col">Action</th>
     
    </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
    <tr>
      <th scope="row"><%= author.id %></th>
      <td><%= author.name %></td>
      <td><%= author.about %></td>
      <td><%= author.experience %> Year</td>
      <td><%= author.dob %></td>
      <td><%= author.address %></td>
      <td><%= author.email %></td>
      <td><%= author.created_at %></td>
      <td><%= author.updated_at %></td>
      <td><%= link_to 'More info', personal_details_author_path(author) %></td>
      
       
    </tr>
    <% end %>
    
  </tbody>
</table>

app/views/authors/new.html.erb
<h1 style="text-align:center;color:white;background-color:red">Enter Author Detail</h1>

<%= form_with model: @author do |f| %>
  <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
      <strong><%= f.label :enter_author_name %></strong>
      <%= f.text_field :name, placeholder: "Enter Author Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :about %></strong>
      <%= f.text_field :about, placeholder: "Enter about Author", autofocus: true %>
    
    </div>

    <div class="column mb-3">
      <strong><%= f.label :enter_experience %></strong>
      <%= f.number_field :experience, placeholder: "Enter Experience Year", autofocus: true %>
    
    </div>
  
    <div class="row mb-3">
      <strong><%= f.label :total_written_books %></strong>
      <%= f.number_field :written_books, placeholder: "Image of book", autofocus: true %>
    
    </div>

    <div class="column mb-3">
      <strong><%= f.label :date_of_birth %></strong>
      <%= f.date_field :dob, placeholder: "", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :author_email %></strong>
      <%= f.email_field :email, placeholder: "Write author's email", autofocus: true %>
    
    </div>

    <div class="row mb-3">
      <strong><%= f.label :authors_address %></strong>
      <%= f.text_field :address, placeholder: "Enter Authors Address", autofocus: true %>
    
    </div>    
 
    <div class="row mb-3">
      <Strong><%= f.label :Chhose_Your_Profile_Pic %></strong>
      <%= f.file_field :pic %>
    
    </div>

    

    
  
  <%= f.submit "submit", class:"btn btn-success " %>
  </div>

  
  
<%end%>

app/views/authors/personal_details.html.erb
<h1 style="text-align:center;color:white;background-color:red"> Author Information</h1>

  <div class="container">
  <div class="row">
    <div class="col-9"><h2 style="text-align:left;color:blue">Author Information</h2></div><hr>
    <div class="col-4"><div class="feature-image">
       
        <%= image_tag @author.pic, :size=>"287x400" if @author.pic.attached? %>
        
        
      </div>
    
    </div>
    <div class="col-6 ">

    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">Name :- <%= @author.name %></h3>
    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">About :-<%= @author.about %></h3>
    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">Experience :- <%= @author.experience %> Year</h3>
    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">Date Of Birth :- <%= @author.dob %></h3>
    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">Email :- <%= @author.email %></h3>
    <br><h3 class="d-flex justify-content-between align-item:centre mx-5">Address :- <%= @author.address %></h3>

    <h5 style="color:red">Tap to see more <%= link_to 'related author book', user_path, class: "btn btn-info" %>and give your fedback</h5>

    
    </div>
    
  </div>
  <%= link_to 'Edit Author', edit_author_path(@author), class: "btn btn-warning" %>
   <%= link_to "Delete Author", author_path(@author), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,class: "btn btn-danger "%>
</div>

app/views/authors/show.html.erb
<h1 style="text-align:center;color:white;background-color:red"> Author Detail</h1>

<div class="container">
  <div class="row">
    <div class="col-9"><h2 style="text-align:left;color:blue">Author Information</h2></div><hr>
    <div class="col-4"><div class="feature-image">
       
        <%= image_tag @author.pic, :size=>"287x400" if @author.pic.attached? %>
        
        
      </div>
    
    </div>
    <div class="col-6 ">
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">Name :- <%= @author.name %></h2>
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">About :-<%= @author.about %></h2>
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">Experience :- <%= @author.experience %> Year</h2>
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">Date Of Birth :- <%= @author.dob %></h2>
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">Email :- <%= @author.email %></h2>
    <br><h2 class="d-flex justify-content-between align-item:centre mx-5">Address :- <%= @author.address %></h2>

    
    
    
    </div>
    
  </div>

  <%= link_to 'Edit Profile', edit_author_path(@author), class: "btn btn-warning" %>
  
  

app/views/books/edit.html.erb
<h1 style="text-align:center;color:white;background-color:black">Edit Book Information</h1>

<%= form_for @book do |f| %>
    <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
    <%= f.label :enter_book_name %>
    <%= f.text_field :book_name, placeholder: "Enter Book Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
    <%= f.label :details_of_book_in_short %>
    <%= f.text_field :description, placeholder: "Enter Description about book", autofocus: true %>
    
    </div>

    <div class="column mb-3">
    <%= f.label :enter_published_date_of_book %>
    <%= f.text_field :published_date, placeholder: "Enter Published date", autofocus: true %>
    
    </div>
  
    <div class="row mb-3">
    <%= f.label :coverpage_of_book %>
    <%= f.file_field :image, placeholder: "Image of book", autofocus: true %>
    
    </div>
    
 
    

    

    
  
  <%= f.submit "submit", class:"btn btn-success " %>
  </div>

  
  
<%end%>

app/views/books/index.html.erb
<h1 style="text-align:center;color:white;background-color:red;mt-3">Book Details</h1>


<div class="book-index-grid d-flex  flex-wrap">
  <% @book.each do |book| %>


  <div class="card m-2 " style="width: 18rem;">
  
  <%= image_tag book.image, :size=>"287x400" if book.image.attached? %>
    <div class="card-body">
       <h5 class="card-title"><b>Book Name :-  </b><%= link_to book.book_name, book %></h5>
       <p class="card-text"><b>Published Date :- </b> <%= book.published_date %></p>
        <p class="card-text"><b>Reviews :- </b><%= book.reviews.count %></p>

       <% if user_signed_in? %>
       <%= link_to 'Edit Book', edit_book_path(book), class: "btn btn-warning" %>
       <%= link_to "Delete Book", book_path(book), data: { turboa_method: :delete, turbo_confirm: 'Are you sure?' } ,class: "btn btn-danger "%>
      <% end %>

    </div>
  </div>

     <% end %>

     
</div>

app/views/books/new.html.erb
<h1 style="text-align:center;color:white;background-color:red">Enter Book Detail</h1>

<%= form_with model: @book do |f| %>
    <div class="container-sm">
    
  
    <div class="row mb-3 mt-5">
    
    <%= f.label :enter_book_name %>
    <%= f.text_field :book_name, placeholder: "Enter Book Name", autofocus: true %>
    
    </div>

    <div class="row mb-3">
    <%= f.label :details_of_book_in_short %>
    <%= f.text_field :description, placeholder: "Enter Description about book", autofocus: true %>
    
    </div>

    <div class="column mb-3">
    <%= f.label :enter_published_date_of_book %>
   
    <%= f.text_field :published_date %>
    
    </div>
  
    <div class="row mb-3">
    <%= f.label :coverpage_of_book %>
    <%= f.file_field :image, placeholder: "Image of book", autofocus: true %>
    
    </div>
    
 
  <%= f.submit "submit", class:"btn btn-success " %>
  </div>

<%end%>

app/views/books/show.html.erb
<h1 style="text-align:center;color:white;background-color:black">Details Of Book</h1>
<div class="container">
  <div class="row">
    <div class="col-9"><h2 style="text-align:left;color:blue">Book Information</h2></div><hr>
      <div class="col-4"><div class="feature-image">
        <%= image_tag @book.image, :size=>"287x400" if @book.image.attached? %>
      </div>
    </div>
    <div class="col-6">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Book Name</th>
            <th scope="col">Book Description</th>
            <th scope="col">Book Published Date</th>
            <th scope="col">Author Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @book.book_name%></td>
            <td><%= @book.description%></td>
            <td><%= @book.published_date%></td>
            <td><%= link_to @authors.name, personal_details_author_path%></td>
          </tr>  
        </tbody>
      </table>
    </div>
  </div>
</div>
<hr><h2>Posted Reviews</h2><hr>
<% @book.reviews.each do |review| %>
  <p>
    <strong>Reviewer Name:</strong>
    <%= review.r_name %>
  </p>

  <p>
    <strong>Reviews:</strong>
    <%= review.r_desc %>
  </p>
  
  <p>
    <strong>Rating:</strong>
    <%= review.star %>
  </p>
  <p>
    <strong>Reviewed At:</strong>
    <%= review.created_at %>
  </p>

  
<% end %>

<hr><h2>Add a Review:</h2><hr>
<%= form_with model: [ @book, @book.reviews.build ] do |form| %>
  <p>
    <strong><%= form.label :reviewer_name %></strong>
    <%= form.text_field :r_name %>
  </p>
  <p>
    <strong><%= form.label :body_of_your_review %></strong>
    <%= form.text_area :r_desc %>
  </p>
  <p>
    <strong><%= form.label :rating %></strong>
    <span class="select">
        <%= form.text_field :star, collection: Review::STAR, prompt: "Select Your Rating" %>
    </span>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>



<div class="container mt-5">
    <%= link_to 'Edit Book', edit_book_path(@book), class: "btn btn-warning" %>
    <%= link_to "Delete Book", book_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } ,class: "btn btn-danger "%>
</div>

app/views/layouts/_footer.html.erb
<div class="card text-center " style="background-color: blue;">
  <div class="card-header">
    <ul class="nav nav-pills card-header-pills">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg .text-light" style="background-color: blue; ">
  <div class="container-fluid".text-light:>
    <a class="nav-link active text-black" aria-current="page" <%=link_to "Book Reviews", root_path%></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">     
        <li class="nav-item " >
          <a class="nav-link active text-black" aria-current="page" <%=link_to "Home", books_path%></a>
        </li>
        
            <% if admin? %>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
              <span class="badge bg-success"> <%= current_user.role  %> </span>
              </a>
              <ul class="dropdown-menu">
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "All Registered Users", users_path %></a></li>
                <li><a class="nav-link active text-black" aria-current="page" <%=link_to "All Authors", authors_path %></a></li>
              </ul>  
            <%  elsif writer? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.email %>
              <span class="badge bg-success"> <%= current_user.role  %> </span>
              </a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link active text-black" aria-current="page" <%=link_to "Post Book", new_book_path%></a></li>
                  <li><a class="nav-link active text-black" aria-current="page" <%=link_to "Your Profile", author_path(1)%></a></li>
                  <li><a class="nav-link active text-black" aria-current="page" <%=link_to "My Books", user_path(current_user)  %></a></li>
                  <li><a class="nav-link active text-black" aria-current="page" <%= link_to "My all reviews", book_reviews_path(Book) %></a></li>
                  
                </ul>
              <%  elsif reviewer? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-black" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.email %>
                  <span class="badge bg-success"> <%= current_user.role  %> </span>
                </a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link active text-black" aria-current="page" <%=link_to "My Profile" %></a></li>
                  <li><a class="nav-link active text-black" aria-current="page" <%=link_to "Add Review", books_path(@book) %></a></li>
                  <li><a class="nav-link active text-black" aria-current="page" <%= link_to "My all reviews", book_reviews_path(Book) %></a></li>
                </ul>
              <% end %>
            
            </li>
          <div class="navbar-end">
            <div class="navbar-item">
            <div class="buttons">
            <% if user_signed_in? %>      
              <%= link_to "Log Out" , destroy_user_session_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "btn btn-success"  %> </a>
            <%else%>    
              <%= link_to "Sign up",  new_user_registration_path(@user), class: "btn btn-success" %>
              <%= link_to "Log in",  new_user_session_path(@user), class: "btn btn-success" %>
            <%end%>
          </a>
        </div>
      </div>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookreviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body >
    <%= render 'layouts/navigation' %>
    <main>

        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      


      <div class="container">
        <%= yield %>
      </div>
      
    </main>
  </body>
  <%= render 'layouts/footer' %>
</html>

app/views/reviews/index.html.erb
<h1 style="text-align:center;color:white;background-color:red;mt-3">My all Reviews</h1>

<div class="book-index-grid d-flex  flex-wrap">
  <% @review.each do |review| %>
    <% if current_user.id == review.book.user_id %>
    <div class="card m-2 " style="width: 18rem;">
      <div class="card-body"><h3>My Reviews</h3><hr>
      <p>
          <strong>Book Name:</strong>
          <%= review.book.id %>
          
        </p>
        <p>
          <strong>Book Name:</strong>
          <%= review.book.book_name %>
          
        </p>
        <p>
          <strong>Reviewer Name:</strong>
          <%= review.r_name %>
        </p>
        <p>
          <strong>Reviews:</strong>
          <%= review.r_desc %>
        </p>
        <p>
          <strong>Rating:</strong>
          <%= review.star %>
        </p>
      </div>
      </div>
    <% end %>
  <% end %>
</div>

     

     

app/views/reviews/profile.html.erb
<h1 style="text-align:center;color:white;background-color:red"> Reviewer Detail</h1>


<% @book.reviews.each do |review| %>
  <p>
    <strong>Reviewer Name:</strong>
    <%= review.r_name %>
  </p>

  
  
 
<%end%>
  

app/views/users/index.html.erb
<h1 style="text-align:center;color:white;background-color:red;mt-3">All Registered user</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Serial Number</th>
      <th scope="col">Email</th>
      <th scope="col">Log In Counted</th>
      <th scope="col">Created At</th>
      <th scope="col">Updated At</th>
      <th scope="col">Role Of User</th>
      <th scope="col">Action </th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td><%= user.email %></td>
      <td><%= user.sign_in_count %></td>
      <td><%= user.created_at %></td>
      <td><%= user.updated_at %></td>
      
       <td><span class="badge bg-success"> <%= user.role  %> </span></td> 
      <td><%= link_to "Edit Role", edit_user_path(user), class: "btn btn-warning" %></td>
    </tr>
    <% end %>
    
  </tbody>
</table>